### ISSUE TITLE
SAML URL is broken

### ISSUE THREAD

**Issue by ixtlanian** [thycotic/wpf-docs#24]
Document: (https://docs.thycotic.com/wpf/2.0.0/troubleshooting/ts-qs-3.md)

SAML link at the bottom of the page is broken
The URL in the link is **javascript:window.angularComponentRef.articleNavigate('../../ss/10.8.0/authentication/saml/index.md')**

**Comment by johnmelody962** [comment]
The broken link has been removed. The working link (https://thy.center/ss/link/SAMLWPFauth) remains.
