### ISSUE TITLE
Enable auto populate setting is missing

### ISSUE THREAD

**Issue by ixtlanian** [thycotic/wpf-docs#25]
Document: (https://docs.thycotic.com/wpf/2.0.0/getting-started/settings.md)

The document does not describe **Enable auto populate** setting.

**Comment by johnmelody962** [comment]
Updated screen shot to one that shows Enable Auto Populate setting.

**Comment by ixtlanian** [comment]
@johnmelody962, is there perhaps some delay between the update on your side and when it's available in the Docs?
I just checked the document and it is still the old version (Last Update: 6/30/20).
I checked from the incognito window to ensure that there's no browser caching issues.

**Comment by johnmelody962** [comment]
Hi Leon,

I should have waited until the change was published to close that one. My apologies!
The change is staged and ready for publication; I was just waiting for a couple of other
changes to push them all at once. I'll have it up by tomorrow morning at the latest.

**Comment by johnmelody962** [comment]
Hello Leon, Sorry this too a while. Yes there is some delay after posting changes for the changes to propagate to the web server. I pushed the changes a few minutes ago and I'll keep checking to see when they've propagated. Thanks for your patience!

**Comment by johnmelody962** [comment]
All set now Leon!
